### ISSUE TITLE
[FEATURE] Character color modification and addition

### ISSUE THREAD

**Issue by JhohannesK** [JhohannesK/TipoHiZ#131]
### Is this a unique feature?

- [X] I have checked "open" AND "closed" issues and this is not a duplicate

### Is your feature request related to a problem/unavailable functionality? Please describe.

Currently, When character is typed correct, it gets a yellow color. That won't match with all themes.

### Proposed Solution

- [ ] Either use a color from themes or we add new colors to the themes to use for correct characters.
- [ ] Add a color when character is wrong. This can also be given the `destructive` color.

### Screenshots

![image](https://github.com/user-attachments/assets/744463a7-531a-44f1-a713-ebfdfc2f34be)

### Do you want to work on this issue?

No

**Comment by ishita-babar** [comment]
To implement this feature, I would first identify the correct colors to use for the text editor based on the project’s existing theme. If no suitable colors exist, I would propose adding a green color for correct characters and a red (destructive) color for wrong characters. Next, I would create a function that compares the user’s input with the reference string. As each character is typed, the function will check if it matches the corresponding character in the correct string. If it matches, I will apply the correct color; otherwise, I will apply the wrong color. This can be done by adding or modifying CSS classes dynamically. The final step would be to ensure that the user interface updates in real-time, so the user receives instant visual feedback. This solution would improve the overall user experience by clearly distinguishing between correct and incorrect input.

**Comment by JhohannesK** [comment]
All colors you would decide to use should be from the ones defined in the tailwind config.
Like you're saying, you'd be adding a `green` color when correct...that color should be a color defined as part of the theme color.

I'm assigning it to you.

**Comment by JhohannesK** [comment]
https://discord.gg/8Z67Fv8z 

you can join our discord and ask all your questions there.
